import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTrigger,
} from "@/components/sheet";
import { Button } from "@/components/button";
import { Dialog, DialogHeader, DialogTrigger } from "@/components/dialog";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sheet & Dialog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen items-center justify-center gap-2 bg-background">
        <Sheet>
          <SheetTrigger asChild>
            <Button variant="destructive">Open Sheet</Button>
          </SheetTrigger>

          <SheetContent>
            <SheetHeader>Sheet</SheetHeader>
          </SheetContent>
        </Sheet>

        <Dialog>
          <DialogTrigger asChild>
            <Button>Open Dialog</Button>
          </DialogTrigger>

          <SheetContent>
            <DialogHeader>Dialog</DialogHeader>
          </SheetContent>
        </Dialog>
      </main>
    </>
  );
};

export default Home;
